-- Create configuracion table
CREATE TABLE IF NOT EXISTS public.configuracion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_negocio TEXT DEFAULT 'Mi Negocio',
    razon_social TEXT DEFAULT '',
    rut TEXT DEFAULT '',
    direccion TEXT DEFAULT '',
    telefono TEXT DEFAULT '',
    email TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.configuracion ENABLE ROW LEVEL SECURITY;

-- Allow read access to authenticated users
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'configuracion' 
        AND policyname = 'Enable read access for authenticated users'
    ) THEN
        CREATE POLICY "Enable read access for authenticated users" ON public.configuracion
            FOR SELECT USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- Allow update access to authenticated users (or restrict to admin if needed)
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies 
        WHERE tablename = 'configuracion' 
        AND policyname = 'Enable update access for authenticated users'
    ) THEN
        CREATE POLICY "Enable update access for authenticated users" ON public.configuracion
            FOR UPDATE USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- Insert default row if not exists
INSERT INTO public.configuracion (id, nombre_negocio)
SELECT 1, 'Mi Panadería'
WHERE NOT EXISTS (SELECT 1 FROM public.configuracion);
